//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvioMailSms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.130.37.40;Initial Catalog=Eximagen_NuevaB;Persist Security Info=Tr" +
            "ue;User ID=sa;Password=\"2NC]>=f.N^\"")]
        public string Eximagen_NuevaBConnectionString {
            get {
                return ((string)(this["Eximagen_NuevaBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.130.37.40;Initial Catalog=EximagenElectro;Persist Security Info=Tr" +
            "ue;User ID=sa;Password=\"2NC]>=f.N^\"")]
        public string EximagenElectroConnectionString {
            get {
                return ((string)(this["EximagenElectroConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.130.37.40;Initial Catalog=OE_SEGURIDAD;Persist Security Info=True;" +
            "User ID=sa;Password=\"2NC]>=f.N^\"")]
        public string OE_SEGURIDADConnectionString {
            get {
                return ((string)(this["OE_SEGURIDADConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.130.37.40;Initial Catalog=Eximagen_NuevaB;User ID=qacg;Password=Ex" +
            "1m4g3n2016")]
        public string Eximagen_NuevaBConnectionString1 {
            get {
                return ((string)(this["Eximagen_NuevaBConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.130.37.40;Initial Catalog=OE_SEGURIDAD;User ID=qacg;Password=Ex1m4" +
            "g3n2016")]
        public string OE_SEGURIDADConnectionString1 {
            get {
                return ((string)(this["OE_SEGURIDADConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.130.37.40;Initial Catalog=Eximagen_NuevaB;User ID=sa;Password=\"2NC" +
            "]>=f.N^\"")]
        public string Eximagen_NuevaBConnectionString2 {
            get {
                return ((string)(this["Eximagen_NuevaBConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.130.37.40;Initial Catalog=EximagenCache;User ID=sa;Password=\"2NC]>" +
            "=f.N^\"")]
        public string EximagenCacheConnectionString {
            get {
                return ((string)(this["EximagenCacheConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.130.37.40;Initial Catalog=Eximagen_NuevaB;Persist Security Info=Tr" +
            "ue;User ID=sapdb;Password=Pa$$w0rd01")]
        public string Eximagen_NuevaBConnectionString3 {
            get {
                return ((string)(this["Eximagen_NuevaBConnectionString3"]));
            }
        }
    }
}
