#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvioMailSms.Modelos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EximagenElectro")]
	public partial class ElectroDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTBL_NOTIFICACION_DATOS(TBL_NOTIFICACION_DATOS instance);
    partial void UpdateTBL_NOTIFICACION_DATOS(TBL_NOTIFICACION_DATOS instance);
    partial void DeleteTBL_NOTIFICACION_DATOS(TBL_NOTIFICACION_DATOS instance);
    partial void InsertTBL_NOTIFICACION_EXCLUIR(TBL_NOTIFICACION_EXCLUIR instance);
    partial void UpdateTBL_NOTIFICACION_EXCLUIR(TBL_NOTIFICACION_EXCLUIR instance);
    partial void DeleteTBL_NOTIFICACION_EXCLUIR(TBL_NOTIFICACION_EXCLUIR instance);
    partial void InsertTBL_NOTIFICACION_FACT(TBL_NOTIFICACION_FACT instance);
    partial void UpdateTBL_NOTIFICACION_FACT(TBL_NOTIFICACION_FACT instance);
    partial void DeleteTBL_NOTIFICACION_FACT(TBL_NOTIFICACION_FACT instance);
    partial void InsertTBL_XML_MANHATTAN(TBL_XML_MANHATTAN instance);
    partial void UpdateTBL_XML_MANHATTAN(TBL_XML_MANHATTAN instance);
    partial void DeleteTBL_XML_MANHATTAN(TBL_XML_MANHATTAN instance);
    #endregion
		
		public ElectroDataContext() : 
				base(global::EnvioMailSms.Properties.Settings.Default.EximagenElectroConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ElectroDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ElectroDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ElectroDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ElectroDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_NOTIFICACION_DATOS> TBL_NOTIFICACION_DATOS
		{
			get
			{
				return this.GetTable<TBL_NOTIFICACION_DATOS>();
			}
		}
		
		public System.Data.Linq.Table<TBL_NOTIFICACION_EXCLUIR> TBL_NOTIFICACION_EXCLUIR
		{
			get
			{
				return this.GetTable<TBL_NOTIFICACION_EXCLUIR>();
			}
		}
		
		public System.Data.Linq.Table<TBL_NOTIFICACION_FACT> TBL_NOTIFICACION_FACT
		{
			get
			{
				return this.GetTable<TBL_NOTIFICACION_FACT>();
			}
		}
		
		public System.Data.Linq.Table<TBL_XML_MANHATTAN> TBL_XML_MANHATTAN
		{
			get
			{
				return this.GetTable<TBL_XML_MANHATTAN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_NOTIFICACION_DATOS")]
	public partial class TBL_NOTIFICACION_DATOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CardCode;
		
		private string _Mail;
		
		private string _Cel;
		
		private System.Nullable<System.DateTime> _Edited;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCardCodeChanging(string value);
    partial void OnCardCodeChanged();
    partial void OnMailChanging(string value);
    partial void OnMailChanged();
    partial void OnCelChanging(string value);
    partial void OnCelChanged();
    partial void OnEditedChanging(System.Nullable<System.DateTime> value);
    partial void OnEditedChanged();
    #endregion
		
		public TBL_NOTIFICACION_DATOS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardCode", DbType="VarChar(10)")]
		public string CardCode
		{
			get
			{
				return this._CardCode;
			}
			set
			{
				if ((this._CardCode != value))
				{
					this.OnCardCodeChanging(value);
					this.SendPropertyChanging();
					this._CardCode = value;
					this.SendPropertyChanged("CardCode");
					this.OnCardCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="VarChar(40)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this.OnMailChanging(value);
					this.SendPropertyChanging();
					this._Mail = value;
					this.SendPropertyChanged("Mail");
					this.OnMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cel", DbType="VarChar(10)")]
		public string Cel
		{
			get
			{
				return this._Cel;
			}
			set
			{
				if ((this._Cel != value))
				{
					this.OnCelChanging(value);
					this.SendPropertyChanging();
					this._Cel = value;
					this.SendPropertyChanged("Cel");
					this.OnCelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edited", DbType="DateTime")]
		public System.Nullable<System.DateTime> Edited
		{
			get
			{
				return this._Edited;
			}
			set
			{
				if ((this._Edited != value))
				{
					this.OnEditedChanging(value);
					this.SendPropertyChanging();
					this._Edited = value;
					this.SendPropertyChanged("Edited");
					this.OnEditedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_NOTIFICACION_EXCLUIR")]
	public partial class TBL_NOTIFICACION_EXCLUIR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CardCode;
		
		private System.Nullable<bool> _Mail;
		
		private System.Nullable<bool> _SMS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCardCodeChanging(string value);
    partial void OnCardCodeChanged();
    partial void OnMailChanging(System.Nullable<bool> value);
    partial void OnMailChanged();
    partial void OnSMSChanging(System.Nullable<bool> value);
    partial void OnSMSChanged();
    #endregion
		
		public TBL_NOTIFICACION_EXCLUIR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardCode", DbType="VarChar(7)")]
		public string CardCode
		{
			get
			{
				return this._CardCode;
			}
			set
			{
				if ((this._CardCode != value))
				{
					this.OnCardCodeChanging(value);
					this.SendPropertyChanging();
					this._CardCode = value;
					this.SendPropertyChanged("CardCode");
					this.OnCardCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="Bit")]
		public System.Nullable<bool> Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this.OnMailChanging(value);
					this.SendPropertyChanging();
					this._Mail = value;
					this.SendPropertyChanged("Mail");
					this.OnMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMS", DbType="Bit")]
		public System.Nullable<bool> SMS
		{
			get
			{
				return this._SMS;
			}
			set
			{
				if ((this._SMS != value))
				{
					this.OnSMSChanging(value);
					this.SendPropertyChanging();
					this._SMS = value;
					this.SendPropertyChanged("SMS");
					this.OnSMSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_NOTIFICACION_FACT")]
	public partial class TBL_NOTIFICACION_FACT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _DocNum;
		
		private System.Nullable<int> _EnviadoMail;
		
		private System.Nullable<int> _EnviadoSMS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDocNumChanging(System.Nullable<int> value);
    partial void OnDocNumChanged();
    partial void OnEnviadoMailChanging(System.Nullable<int> value);
    partial void OnEnviadoMailChanged();
    partial void OnEnviadoSMSChanging(System.Nullable<int> value);
    partial void OnEnviadoSMSChanged();
    #endregion
		
		public TBL_NOTIFICACION_FACT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocNum", DbType="Int")]
		public System.Nullable<int> DocNum
		{
			get
			{
				return this._DocNum;
			}
			set
			{
				if ((this._DocNum != value))
				{
					this.OnDocNumChanging(value);
					this.SendPropertyChanging();
					this._DocNum = value;
					this.SendPropertyChanged("DocNum");
					this.OnDocNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnviadoMail", DbType="Int")]
		public System.Nullable<int> EnviadoMail
		{
			get
			{
				return this._EnviadoMail;
			}
			set
			{
				if ((this._EnviadoMail != value))
				{
					this.OnEnviadoMailChanging(value);
					this.SendPropertyChanging();
					this._EnviadoMail = value;
					this.SendPropertyChanged("EnviadoMail");
					this.OnEnviadoMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnviadoSMS", DbType="Int")]
		public System.Nullable<int> EnviadoSMS
		{
			get
			{
				return this._EnviadoSMS;
			}
			set
			{
				if ((this._EnviadoSMS != value))
				{
					this.OnEnviadoSMSChanging(value);
					this.SendPropertyChanging();
					this._EnviadoSMS = value;
					this.SendPropertyChanged("EnviadoSMS");
					this.OnEnviadoSMSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_XML_MANHATTAN")]
	public partial class TBL_XML_MANHATTAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _UUID;
		
		private System.Nullable<int> _FolioWeb;
		
		private System.Nullable<int> _IdTienda;
		
		private System.Xml.Linq.XElement _XMLData;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUUIDChanging(string value);
    partial void OnUUIDChanged();
    partial void OnFolioWebChanging(System.Nullable<int> value);
    partial void OnFolioWebChanged();
    partial void OnIdTiendaChanging(System.Nullable<int> value);
    partial void OnIdTiendaChanged();
    partial void OnXMLDataChanging(System.Xml.Linq.XElement value);
    partial void OnXMLDataChanged();
    #endregion
		
		public TBL_XML_MANHATTAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UUID", DbType="VarChar(50)")]
		public string UUID
		{
			get
			{
				return this._UUID;
			}
			set
			{
				if ((this._UUID != value))
				{
					this.OnUUIDChanging(value);
					this.SendPropertyChanging();
					this._UUID = value;
					this.SendPropertyChanged("UUID");
					this.OnUUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FolioWeb", DbType="Int")]
		public System.Nullable<int> FolioWeb
		{
			get
			{
				return this._FolioWeb;
			}
			set
			{
				if ((this._FolioWeb != value))
				{
					this.OnFolioWebChanging(value);
					this.SendPropertyChanging();
					this._FolioWeb = value;
					this.SendPropertyChanged("FolioWeb");
					this.OnFolioWebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTienda", DbType="Int")]
		public System.Nullable<int> IdTienda
		{
			get
			{
				return this._IdTienda;
			}
			set
			{
				if ((this._IdTienda != value))
				{
					this.OnIdTiendaChanging(value);
					this.SendPropertyChanging();
					this._IdTienda = value;
					this.SendPropertyChanged("IdTienda");
					this.OnIdTiendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XMLData", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement XMLData
		{
			get
			{
				return this._XMLData;
			}
			set
			{
				if ((this._XMLData != value))
				{
					this.OnXMLDataChanging(value);
					this.SendPropertyChanging();
					this._XMLData = value;
					this.SendPropertyChanged("XMLData");
					this.OnXMLDataChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
