#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvioMailSms.Modelos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EximagenCache")]
	public partial class EximagenCacheDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertValidaTiendaMensaje(ValidaTiendaMensaje instance);
    partial void UpdateValidaTiendaMensaje(ValidaTiendaMensaje instance);
    partial void DeleteValidaTiendaMensaje(ValidaTiendaMensaje instance);
    partial void InsertCambioVista(CambioVista instance);
    partial void UpdateCambioVista(CambioVista instance);
    partial void DeleteCambioVista(CambioVista instance);
    partial void InsertEstilosPorVista(EstilosPorVista instance);
    partial void UpdateEstilosPorVista(EstilosPorVista instance);
    partial void DeleteEstilosPorVista(EstilosPorVista instance);
    #endregion
		
		public EximagenCacheDataContext() : 
				base(global::EnvioMailSms.Properties.Settings.Default.EximagenCacheConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EximagenCacheDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EximagenCacheDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EximagenCacheDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EximagenCacheDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ValidaTiendaMensaje> ValidaTiendaMensaje
		{
			get
			{
				return this.GetTable<ValidaTiendaMensaje>();
			}
		}
		
		public System.Data.Linq.Table<CambioVista> CambioVista
		{
			get
			{
				return this.GetTable<CambioVista>();
			}
		}
		
		public System.Data.Linq.Table<EstilosPorVista> EstilosPorVista
		{
			get
			{
				return this.GetTable<EstilosPorVista>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ValidaTiendaMensaje")]
	public partial class ValidaTiendaMensaje : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _docnum;
		
		private bool _envio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndocnumChanging(int value);
    partial void OndocnumChanged();
    partial void OnenvioChanging(bool value);
    partial void OnenvioChanged();
    #endregion
		
		public ValidaTiendaMensaje()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_docnum", DbType="Int NOT NULL")]
		public int docnum
		{
			get
			{
				return this._docnum;
			}
			set
			{
				if ((this._docnum != value))
				{
					this.OndocnumChanging(value);
					this.SendPropertyChanging();
					this._docnum = value;
					this.SendPropertyChanged("docnum");
					this.OndocnumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_envio", DbType="Bit NOT NULL")]
		public bool envio
		{
			get
			{
				return this._envio;
			}
			set
			{
				if ((this._envio != value))
				{
					this.OnenvioChanging(value);
					this.SendPropertyChanging();
					this._envio = value;
					this.SendPropertyChanged("envio");
					this.OnenvioChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CambioVista")]
	public partial class CambioVista : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Cliente;
		
		private string _Dominio;
		
		private string _SubDominio;
		
		private string _Moneda;
		
		private string _CardCode;
		
		private string _Language;
		
		private string _SistemaMetrico;
		
		private System.Nullable<int> _ListaEspecial;
		
		private bool _VerRegistro;
		
		private bool _ValidaOpenPay;
		
		private System.Nullable<bool> _ValidaMargenDecorado;
		
		private System.Nullable<int> _RolTienda;
		
		private System.Nullable<int> _PermisosTienda;
		
		private EntitySet<EstilosPorVista> _EstilosPorVista;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnClienteChanging(string value);
    partial void OnClienteChanged();
    partial void OnDominioChanging(string value);
    partial void OnDominioChanged();
    partial void OnSubDominioChanging(string value);
    partial void OnSubDominioChanged();
    partial void OnMonedaChanging(string value);
    partial void OnMonedaChanged();
    partial void OnCardCodeChanging(string value);
    partial void OnCardCodeChanged();
    partial void OnLanguageChanging(string value);
    partial void OnLanguageChanged();
    partial void OnSistemaMetricoChanging(string value);
    partial void OnSistemaMetricoChanged();
    partial void OnListaEspecialChanging(System.Nullable<int> value);
    partial void OnListaEspecialChanged();
    partial void OnVerRegistroChanging(bool value);
    partial void OnVerRegistroChanged();
    partial void OnValidaOpenPayChanging(bool value);
    partial void OnValidaOpenPayChanged();
    partial void OnValidaMargenDecoradoChanging(System.Nullable<bool> value);
    partial void OnValidaMargenDecoradoChanged();
    partial void OnRolTiendaChanging(System.Nullable<int> value);
    partial void OnRolTiendaChanged();
    partial void OnPermisosTiendaChanging(System.Nullable<int> value);
    partial void OnPermisosTiendaChanged();
    #endregion
		
		public CambioVista()
		{
			this._EstilosPorVista = new EntitySet<EstilosPorVista>(new Action<EstilosPorVista>(this.attach_EstilosPorVista), new Action<EstilosPorVista>(this.detach_EstilosPorVista));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cliente", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Cliente
		{
			get
			{
				return this._Cliente;
			}
			set
			{
				if ((this._Cliente != value))
				{
					this.OnClienteChanging(value);
					this.SendPropertyChanging();
					this._Cliente = value;
					this.SendPropertyChanged("Cliente");
					this.OnClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dominio", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Dominio
		{
			get
			{
				return this._Dominio;
			}
			set
			{
				if ((this._Dominio != value))
				{
					this.OnDominioChanging(value);
					this.SendPropertyChanging();
					this._Dominio = value;
					this.SendPropertyChanged("Dominio");
					this.OnDominioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubDominio", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string SubDominio
		{
			get
			{
				return this._SubDominio;
			}
			set
			{
				if ((this._SubDominio != value))
				{
					this.OnSubDominioChanging(value);
					this.SendPropertyChanging();
					this._SubDominio = value;
					this.SendPropertyChanged("SubDominio");
					this.OnSubDominioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Moneda", DbType="NChar(3)")]
		public string Moneda
		{
			get
			{
				return this._Moneda;
			}
			set
			{
				if ((this._Moneda != value))
				{
					this.OnMonedaChanging(value);
					this.SendPropertyChanging();
					this._Moneda = value;
					this.SendPropertyChanged("Moneda");
					this.OnMonedaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardCode", DbType="VarChar(15)")]
		public string CardCode
		{
			get
			{
				return this._CardCode;
			}
			set
			{
				if ((this._CardCode != value))
				{
					this.OnCardCodeChanging(value);
					this.SendPropertyChanging();
					this._CardCode = value;
					this.SendPropertyChanged("CardCode");
					this.OnCardCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Language", DbType="VarChar(50)")]
		public string Language
		{
			get
			{
				return this._Language;
			}
			set
			{
				if ((this._Language != value))
				{
					this.OnLanguageChanging(value);
					this.SendPropertyChanging();
					this._Language = value;
					this.SendPropertyChanged("Language");
					this.OnLanguageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SistemaMetrico", DbType="NVarChar(3)")]
		public string SistemaMetrico
		{
			get
			{
				return this._SistemaMetrico;
			}
			set
			{
				if ((this._SistemaMetrico != value))
				{
					this.OnSistemaMetricoChanging(value);
					this.SendPropertyChanging();
					this._SistemaMetrico = value;
					this.SendPropertyChanged("SistemaMetrico");
					this.OnSistemaMetricoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListaEspecial", DbType="Int")]
		public System.Nullable<int> ListaEspecial
		{
			get
			{
				return this._ListaEspecial;
			}
			set
			{
				if ((this._ListaEspecial != value))
				{
					this.OnListaEspecialChanging(value);
					this.SendPropertyChanging();
					this._ListaEspecial = value;
					this.SendPropertyChanged("ListaEspecial");
					this.OnListaEspecialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerRegistro", DbType="Bit NOT NULL")]
		public bool VerRegistro
		{
			get
			{
				return this._VerRegistro;
			}
			set
			{
				if ((this._VerRegistro != value))
				{
					this.OnVerRegistroChanging(value);
					this.SendPropertyChanging();
					this._VerRegistro = value;
					this.SendPropertyChanged("VerRegistro");
					this.OnVerRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValidaOpenPay", DbType="Bit NOT NULL")]
		public bool ValidaOpenPay
		{
			get
			{
				return this._ValidaOpenPay;
			}
			set
			{
				if ((this._ValidaOpenPay != value))
				{
					this.OnValidaOpenPayChanging(value);
					this.SendPropertyChanging();
					this._ValidaOpenPay = value;
					this.SendPropertyChanged("ValidaOpenPay");
					this.OnValidaOpenPayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValidaMargenDecorado", DbType="Bit")]
		public System.Nullable<bool> ValidaMargenDecorado
		{
			get
			{
				return this._ValidaMargenDecorado;
			}
			set
			{
				if ((this._ValidaMargenDecorado != value))
				{
					this.OnValidaMargenDecoradoChanging(value);
					this.SendPropertyChanging();
					this._ValidaMargenDecorado = value;
					this.SendPropertyChanged("ValidaMargenDecorado");
					this.OnValidaMargenDecoradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RolTienda", DbType="Int")]
		public System.Nullable<int> RolTienda
		{
			get
			{
				return this._RolTienda;
			}
			set
			{
				if ((this._RolTienda != value))
				{
					this.OnRolTiendaChanging(value);
					this.SendPropertyChanging();
					this._RolTienda = value;
					this.SendPropertyChanged("RolTienda");
					this.OnRolTiendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermisosTienda", DbType="Int")]
		public System.Nullable<int> PermisosTienda
		{
			get
			{
				return this._PermisosTienda;
			}
			set
			{
				if ((this._PermisosTienda != value))
				{
					this.OnPermisosTiendaChanging(value);
					this.SendPropertyChanging();
					this._PermisosTienda = value;
					this.SendPropertyChanged("PermisosTienda");
					this.OnPermisosTiendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CambioVista_EstilosPorVista", Storage="_EstilosPorVista", ThisKey="ID", OtherKey="IDCliente")]
		public EntitySet<EstilosPorVista> EstilosPorVista
		{
			get
			{
				return this._EstilosPorVista;
			}
			set
			{
				this._EstilosPorVista.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_EstilosPorVista(EstilosPorVista entity)
		{
			this.SendPropertyChanging();
			entity.CambioVista = this;
		}
		
		private void detach_EstilosPorVista(EstilosPorVista entity)
		{
			this.SendPropertyChanging();
			entity.CambioVista = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EstilosPorVista")]
	public partial class EstilosPorVista : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _IDCliente;
		
		private string _Campo;
		
		private string _Valor;
		
		private EntityRef<CambioVista> _CambioVista;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnIDClienteChanging(int value);
    partial void OnIDClienteChanged();
    partial void OnCampoChanging(string value);
    partial void OnCampoChanged();
    partial void OnValorChanging(string value);
    partial void OnValorChanged();
    #endregion
		
		public EstilosPorVista()
		{
			this._CambioVista = default(EntityRef<CambioVista>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCliente", DbType="Int NOT NULL")]
		public int IDCliente
		{
			get
			{
				return this._IDCliente;
			}
			set
			{
				if ((this._IDCliente != value))
				{
					if (this._CambioVista.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDClienteChanging(value);
					this.SendPropertyChanging();
					this._IDCliente = value;
					this.SendPropertyChanged("IDCliente");
					this.OnIDClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Campo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Campo
		{
			get
			{
				return this._Campo;
			}
			set
			{
				if ((this._Campo != value))
				{
					this.OnCampoChanging(value);
					this.SendPropertyChanging();
					this._Campo = value;
					this.SendPropertyChanged("Campo");
					this.OnCampoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CambioVista_EstilosPorVista", Storage="_CambioVista", ThisKey="IDCliente", OtherKey="ID", IsForeignKey=true)]
		public CambioVista CambioVista
		{
			get
			{
				return this._CambioVista.Entity;
			}
			set
			{
				CambioVista previousValue = this._CambioVista.Entity;
				if (((previousValue != value) 
							|| (this._CambioVista.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CambioVista.Entity = null;
						previousValue.EstilosPorVista.Remove(this);
					}
					this._CambioVista.Entity = value;
					if ((value != null))
					{
						value.EstilosPorVista.Add(this);
						this._IDCliente = value.ID;
					}
					else
					{
						this._IDCliente = default(int);
					}
					this.SendPropertyChanged("CambioVista");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
