#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvioMailSms.Modelos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OE_SEGURIDAD")]
	public partial class SeguridadDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertQACG_CLIENTE_EXTERNO(QACG_CLIENTE_EXTERNO instance);
    partial void UpdateQACG_CLIENTE_EXTERNO(QACG_CLIENTE_EXTERNO instance);
    partial void DeleteQACG_CLIENTE_EXTERNO(QACG_CLIENTE_EXTERNO instance);
    #endregion
		
		public SeguridadDataContext() : 
				base(global::EnvioMailSms.Properties.Settings.Default.OE_SEGURIDADConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public SeguridadDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SeguridadDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SeguridadDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SeguridadDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<QACG_CLIENTE_EXTERNO> QACG_CLIENTE_EXTERNO
		{
			get
			{
				return this.GetTable<QACG_CLIENTE_EXTERNO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QACG_CLIENTE_EXTERNO")]
	public partial class QACG_CLIENTE_EXTERNO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UID_CLIENTE_EXTERNO;
		
		private System.Guid _UID_CLIENTE;
		
		private string _INO_CLIENTE;
		
		private string _SLOGO;
		
		private string _SNOMBRE;
		
		private string _SPUESTO;
		
		private string _SEMAIL;
		
		private string _SPASSWORD;
		
		private string _STELEFONO;
		
		private System.Nullable<System.Guid> _UID_UserInsert;
		
		private System.Nullable<System.DateTime> _DT_DateInsert;
		
		private System.Nullable<System.Guid> _UID_UserUpdate;
		
		private System.Nullable<System.DateTime> _DT_DateUpdate;
		
		private bool _B_Active;
		
		private bool _BloqEmailFactura;
		
		private bool _BloqEmailOD;
		
		private bool _BloqEmailEmbarque;
		
		private bool _BloqEmailProduccion;
		
		private int _IdTienda;
		
		private bool _IsAdmin;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUID_CLIENTE_EXTERNOChanging(int value);
    partial void OnUID_CLIENTE_EXTERNOChanged();
    partial void OnUID_CLIENTEChanging(System.Guid value);
    partial void OnUID_CLIENTEChanged();
    partial void OnINO_CLIENTEChanging(string value);
    partial void OnINO_CLIENTEChanged();
    partial void OnSLOGOChanging(string value);
    partial void OnSLOGOChanged();
    partial void OnSNOMBREChanging(string value);
    partial void OnSNOMBREChanged();
    partial void OnSPUESTOChanging(string value);
    partial void OnSPUESTOChanged();
    partial void OnSEMAILChanging(string value);
    partial void OnSEMAILChanged();
    partial void OnSPASSWORDChanging(string value);
    partial void OnSPASSWORDChanged();
    partial void OnSTELEFONOChanging(string value);
    partial void OnSTELEFONOChanged();
    partial void OnUID_UserInsertChanging(System.Nullable<System.Guid> value);
    partial void OnUID_UserInsertChanged();
    partial void OnDT_DateInsertChanging(System.Nullable<System.DateTime> value);
    partial void OnDT_DateInsertChanged();
    partial void OnUID_UserUpdateChanging(System.Nullable<System.Guid> value);
    partial void OnUID_UserUpdateChanged();
    partial void OnDT_DateUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnDT_DateUpdateChanged();
    partial void OnB_ActiveChanging(bool value);
    partial void OnB_ActiveChanged();
    partial void OnBloqEmailFacturaChanging(bool value);
    partial void OnBloqEmailFacturaChanged();
    partial void OnBloqEmailODChanging(bool value);
    partial void OnBloqEmailODChanged();
    partial void OnBloqEmailEmbarqueChanging(bool value);
    partial void OnBloqEmailEmbarqueChanged();
    partial void OnBloqEmailProduccionChanging(bool value);
    partial void OnBloqEmailProduccionChanged();
    partial void OnIdTiendaChanging(int value);
    partial void OnIdTiendaChanged();
    partial void OnIsAdminChanging(bool value);
    partial void OnIsAdminChanged();
    #endregion
		
		public QACG_CLIENTE_EXTERNO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UID_CLIENTE_EXTERNO", DbType="Int NOT NULL")]
		public int UID_CLIENTE_EXTERNO
		{
			get
			{
				return this._UID_CLIENTE_EXTERNO;
			}
			set
			{
				if ((this._UID_CLIENTE_EXTERNO != value))
				{
					this.OnUID_CLIENTE_EXTERNOChanging(value);
					this.SendPropertyChanging();
					this._UID_CLIENTE_EXTERNO = value;
					this.SendPropertyChanged("UID_CLIENTE_EXTERNO");
					this.OnUID_CLIENTE_EXTERNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UID_CLIENTE", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UID_CLIENTE
		{
			get
			{
				return this._UID_CLIENTE;
			}
			set
			{
				if ((this._UID_CLIENTE != value))
				{
					this.OnUID_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._UID_CLIENTE = value;
					this.SendPropertyChanged("UID_CLIENTE");
					this.OnUID_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INO_CLIENTE", DbType="VarChar(10)")]
		public string INO_CLIENTE
		{
			get
			{
				return this._INO_CLIENTE;
			}
			set
			{
				if ((this._INO_CLIENTE != value))
				{
					this.OnINO_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._INO_CLIENTE = value;
					this.SendPropertyChanged("INO_CLIENTE");
					this.OnINO_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLOGO", DbType="VarChar(250)")]
		public string SLOGO
		{
			get
			{
				return this._SLOGO;
			}
			set
			{
				if ((this._SLOGO != value))
				{
					this.OnSLOGOChanging(value);
					this.SendPropertyChanging();
					this._SLOGO = value;
					this.SendPropertyChanged("SLOGO");
					this.OnSLOGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNOMBRE", DbType="VarChar(250)")]
		public string SNOMBRE
		{
			get
			{
				return this._SNOMBRE;
			}
			set
			{
				if ((this._SNOMBRE != value))
				{
					this.OnSNOMBREChanging(value);
					this.SendPropertyChanging();
					this._SNOMBRE = value;
					this.SendPropertyChanged("SNOMBRE");
					this.OnSNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPUESTO", DbType="VarChar(50)")]
		public string SPUESTO
		{
			get
			{
				return this._SPUESTO;
			}
			set
			{
				if ((this._SPUESTO != value))
				{
					this.OnSPUESTOChanging(value);
					this.SendPropertyChanging();
					this._SPUESTO = value;
					this.SendPropertyChanged("SPUESTO");
					this.OnSPUESTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEMAIL", DbType="VarChar(250)")]
		public string SEMAIL
		{
			get
			{
				return this._SEMAIL;
			}
			set
			{
				if ((this._SEMAIL != value))
				{
					this.OnSEMAILChanging(value);
					this.SendPropertyChanging();
					this._SEMAIL = value;
					this.SendPropertyChanged("SEMAIL");
					this.OnSEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPASSWORD", DbType="VarChar(MAX)")]
		public string SPASSWORD
		{
			get
			{
				return this._SPASSWORD;
			}
			set
			{
				if ((this._SPASSWORD != value))
				{
					this.OnSPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._SPASSWORD = value;
					this.SendPropertyChanged("SPASSWORD");
					this.OnSPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STELEFONO", DbType="VarChar(50)")]
		public string STELEFONO
		{
			get
			{
				return this._STELEFONO;
			}
			set
			{
				if ((this._STELEFONO != value))
				{
					this.OnSTELEFONOChanging(value);
					this.SendPropertyChanging();
					this._STELEFONO = value;
					this.SendPropertyChanged("STELEFONO");
					this.OnSTELEFONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UID_UserInsert", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UID_UserInsert
		{
			get
			{
				return this._UID_UserInsert;
			}
			set
			{
				if ((this._UID_UserInsert != value))
				{
					this.OnUID_UserInsertChanging(value);
					this.SendPropertyChanging();
					this._UID_UserInsert = value;
					this.SendPropertyChanged("UID_UserInsert");
					this.OnUID_UserInsertChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_DateInsert", DbType="DateTime")]
		public System.Nullable<System.DateTime> DT_DateInsert
		{
			get
			{
				return this._DT_DateInsert;
			}
			set
			{
				if ((this._DT_DateInsert != value))
				{
					this.OnDT_DateInsertChanging(value);
					this.SendPropertyChanging();
					this._DT_DateInsert = value;
					this.SendPropertyChanged("DT_DateInsert");
					this.OnDT_DateInsertChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UID_UserUpdate", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UID_UserUpdate
		{
			get
			{
				return this._UID_UserUpdate;
			}
			set
			{
				if ((this._UID_UserUpdate != value))
				{
					this.OnUID_UserUpdateChanging(value);
					this.SendPropertyChanging();
					this._UID_UserUpdate = value;
					this.SendPropertyChanged("UID_UserUpdate");
					this.OnUID_UserUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_DateUpdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DT_DateUpdate
		{
			get
			{
				return this._DT_DateUpdate;
			}
			set
			{
				if ((this._DT_DateUpdate != value))
				{
					this.OnDT_DateUpdateChanging(value);
					this.SendPropertyChanging();
					this._DT_DateUpdate = value;
					this.SendPropertyChanged("DT_DateUpdate");
					this.OnDT_DateUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B_Active", DbType="Bit NOT NULL")]
		public bool B_Active
		{
			get
			{
				return this._B_Active;
			}
			set
			{
				if ((this._B_Active != value))
				{
					this.OnB_ActiveChanging(value);
					this.SendPropertyChanging();
					this._B_Active = value;
					this.SendPropertyChanged("B_Active");
					this.OnB_ActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloqEmailFactura", DbType="Bit NOT NULL")]
		public bool BloqEmailFactura
		{
			get
			{
				return this._BloqEmailFactura;
			}
			set
			{
				if ((this._BloqEmailFactura != value))
				{
					this.OnBloqEmailFacturaChanging(value);
					this.SendPropertyChanging();
					this._BloqEmailFactura = value;
					this.SendPropertyChanged("BloqEmailFactura");
					this.OnBloqEmailFacturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloqEmailOD", DbType="Bit NOT NULL")]
		public bool BloqEmailOD
		{
			get
			{
				return this._BloqEmailOD;
			}
			set
			{
				if ((this._BloqEmailOD != value))
				{
					this.OnBloqEmailODChanging(value);
					this.SendPropertyChanging();
					this._BloqEmailOD = value;
					this.SendPropertyChanged("BloqEmailOD");
					this.OnBloqEmailODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloqEmailEmbarque", DbType="Bit NOT NULL")]
		public bool BloqEmailEmbarque
		{
			get
			{
				return this._BloqEmailEmbarque;
			}
			set
			{
				if ((this._BloqEmailEmbarque != value))
				{
					this.OnBloqEmailEmbarqueChanging(value);
					this.SendPropertyChanging();
					this._BloqEmailEmbarque = value;
					this.SendPropertyChanged("BloqEmailEmbarque");
					this.OnBloqEmailEmbarqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloqEmailProduccion", DbType="Bit NOT NULL")]
		public bool BloqEmailProduccion
		{
			get
			{
				return this._BloqEmailProduccion;
			}
			set
			{
				if ((this._BloqEmailProduccion != value))
				{
					this.OnBloqEmailProduccionChanging(value);
					this.SendPropertyChanging();
					this._BloqEmailProduccion = value;
					this.SendPropertyChanged("BloqEmailProduccion");
					this.OnBloqEmailProduccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTienda")]
		public int IdTienda
		{
			get
			{
				return this._IdTienda;
			}
			set
			{
				if ((this._IdTienda != value))
				{
					this.OnIdTiendaChanging(value);
					this.SendPropertyChanging();
					this._IdTienda = value;
					this.SendPropertyChanged("IdTienda");
					this.OnIdTiendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAdmin")]
		public bool IsAdmin
		{
			get
			{
				return this._IsAdmin;
			}
			set
			{
				if ((this._IsAdmin != value))
				{
					this.OnIsAdminChanging(value);
					this.SendPropertyChanging();
					this._IsAdmin = value;
					this.SendPropertyChanged("IsAdmin");
					this.OnIsAdminChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
